version: '3.8'

services:
  apache:
    build: .  # Build from the current directory
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html  # Mount index.html
